# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0018_pagenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroArea',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='hero_area_plugin_heroarea', serialize=False, to='cms.CMSPlugin')),
                ('intro_title', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('background_image', models.ImageField(upload_to='hero_area/img/')),
                ('youtube_introduction', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
