# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('hero_area_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortHeroArea',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='hero_area_plugin_shortheroarea', serialize=False, to='cms.CMSPlugin')),
                ('page_title', models.CharField(max_length=100)),
                ('page_message', models.CharField(max_length=150)),
                ('background_image', models.ImageField(upload_to='hero_area/img/')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
