# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_area_plugin', '0003_auto_20180611_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroarea',
            name='introduction',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
