# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 04:36
from __future__ import unicode_literals

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hero_area_plugin', '0004_heroarea_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroarea',
            name='introduction',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', null=True, verbose_name='introduction'),
        ),
    ]
