version: '3.3'

services:
  db:
    image: postgres:9.6
    container_name: hien_portfolio_db
    restart: always
    # command: bash -c "sudo pg_restore --username=postgres -d hien_portfolio_db ./backupdb/hien_portfolio_db_04-11-2018_14-39.sql "
    volumes: 
    #   - psql:/var/lib/postgres/data
      - ./backupdb:/backupdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sinh1996
      - POSTGRES_DB=hien_portfolio_db
  nginx:
    image: nginx:latest
    container_name: hien_portfolio_nginx
    ports:
      - '8014:8012'
    volumes:
      - ./web:/hien_portfolio
      - ./nginx/:/etc/nginx/conf.d
      - ./web/static:/static
      - ./web/media:/media
    depends_on:
      - web
  web:
    build: ./web
    container_name: hien_portfolio_web
    command: bash -c "python manage.py migrate && gunicorn hien_portfolio.wsgi -b 0.0.0.0:8012"
    depends_on:
      - db
    expose:
      - "8012"