# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('contact_me_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallActionSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contact_me_plugin_callactionsection', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='contact_me/img/')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
