# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me_plugin', '0003_callactionsection_image_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callactionsection',
            old_name='image_background',
            new_name='background_image',
        ),
    ]
