# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me_plugin', '0004_auto_20180410_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
