# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_me_plugin', '0005_auto_20180411_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='background_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='contact_me/img/'),
        ),
    ]
