# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('testimonial_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialComponent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='testimonial_plugin_testimonialcomponent', serialize=False, to='cms.CMSPlugin')),
                ('background_image', models.ImageField(upload_to='testimonial/img/')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='testimonialcompnent',
            name='cmsplugin_ptr',
        ),
        migrations.AlterField(
            model_name='testimonialitem',
            name='testimonial_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testimonial_plugin.TestimonialComponent'),
        ),
        migrations.DeleteModel(
            name='TestimonialCompnent',
        ),
    ]
