# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='length',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='roles',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
