# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20180410_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='media_asset',
            field=models.ImageField(default='', upload_to='portfolio/img/'),
        ),
    ]
