# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_pagenode'),
        ('portfolio_app', '0003_auto_20180410_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestWorkSection',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='portfolio_app_latestworksection', serialize=False, to='cms.CMSPlugin')),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
