# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_project_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_homepage_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_list_display',
            field=models.BooleanField(default=True),
        ),
    ]
