# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_auto_20180605_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='top_image',
            field=models.ImageField(blank=True, default='', max_length=500, null=True, upload_to='portfolio/img/top_image/'),
        ),
    ]
