# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='statistic',
            field=models.CharField(default='', max_length=20),
        ),
    ]
