# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_plugin', '0004_auto_20180409_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='fa_icon',
            field=models.CharField(default='', max_length=80),
        ),
    ]
