# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-14 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_plugin', '0005_statistic_fa_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.SmallIntegerField(choices=[(1, 'Android'), (2, 'IOS'), (3, 'React Native'), (4, 'Flutter')], default=1),
        ),
    ]
