# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-06 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me_plugin', '0006_skill_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='statistic_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Number'), (2, 'Percentage'), (3, 'Money')], default=1),
        ),
    ]
